## CSC 478 Assignment 4
### Sarah Cummings

### Question 1: PCA for Reduced Dimensionality in Clustering  with segmentation Dataset
#### A) Load in the image data matrix and  class labels from the segmentation class file. Perform min max normalization.

In [1]:
import numpy as np
import pandas as pd
import sys
import matplotlib.pyplot as plt
%matplotlib inline
import operator
#from sklearn.cross_validation import KFold
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet, SGDRegressor
from sklearn.cluster import KMeans 
from sklearn.cross_validation import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import scale
from sklearn.metrics import completeness_score, homogeneity_score

C:\Users\scummings\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [5]:
#read in the data
img_df = pd.read_csv(r"C:\Users\scummings\Desktop\MyFiles\school\csc478_4\segmentation_data\segmentation_data.txt",encoding = "ISO-8859-1", low_memory=False,header=None)
#img_df.head()
labels = pd.read_csv(r"C:\Users\scummings\Desktop\MyFiles\school\csc478_4\segmentation_data\segmentation_classes.txt", header=None, sep= "\t")
labels.shape

(2100, 2)

In [10]:
#perform min max normalization
min_max_scaler = preprocessing.MinMaxScaler()
np_scaled = min_max_scaler.fit_transform(img_df)
df_norm = pd.DataFrame(np_scaled)
df_norm.head()


0         1    2    3    4         5         6         7         8   \
0  0.430830  0.741667  0.0  0.0  0.0  0.034221  0.000672  0.027329  0.000856   
1  0.335968  0.733333  0.0  0.0  0.0  0.038023  0.000726  0.032298  0.000541   
2  0.885375  0.970833  0.0  0.0  0.0  0.115970  0.002213  0.067081  0.001097   
3  0.181818  0.920833  0.0  0.0  0.0  0.043726  0.001265  0.022360  0.000645   
4  0.379447  0.729167  0.0  0.0  0.0  0.039924  0.000697  0.026087  0.000725   

         9         10        11        12        13        14        15  \
0  0.090111  0.079417  0.061119  0.130943  0.731343  0.014118  0.872865   
1  0.095791  0.085089  0.068483  0.134840  0.729478  0.023529  0.859583   
2  0.085463  0.075365  0.061856  0.120031  0.736940  0.038824  0.827324   
3  0.088562  0.080227  0.059647  0.127046  0.748134  0.014118  0.855787   
4  0.108701  0.101297  0.078056  0.148090  0.748134  0.010588  0.861480   

         16        17        18  
0  0.123711  0.508139  0.831849  
1  0.127393  0.463329  0.836986  
2  0.113402  0.480149  0.844782  
3  0.120029  0.500966  0.825889  
4  0.139912  0.442661  0.823924

In [11]:
df_norm.shape

(2100, 19)

#### B) Perform Kmeans clustering with k=7 and Euclidean Distance. Print the cluster centroid, and compare your 7 clusters to the 7 pre-assigned classes by computing the Completeness and Homogeneity values of the generated clusters.

In [13]:
kmeans = KMeans(n_clusters=7, max_iter=500, verbose=1) # initialization
kmeans.fit(df_norm)



Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 416.912184188
start iteration
done sorting
end inner loop
Iteration 1, inertia 392.26545982
start iteration
done sorting
end inner loop
Iteration 2, inertia 387.137656645
start iteration
done sorting
end inner loop
Iteration 3, inertia 385.010654687
start iteration
done sorting
end inner loop
Iteration 4, inertia 382.214374434
start iteration
done sorting
end inner loop
Iteration 5, inertia 377.411173696
start iteration
done sorting
end inner loop
Iteration 6, inertia 375.358542772
start iteration
done sorting
end inner loop
Iteration 7, inertia 374.390091372
start iteration
done sorting
end inner loop
Iteration 8, inertia 373.768269249
start iteration
done sorting
end inner loop
Iteration 9, inertia 373.345912442
start iteration
done sorting
end inner loop
Iteration 10, inertia 373.053544893
start iteration
done sorting
end inner loop
Iteration 11, inertia 372.608289788
start iteration
done sortin

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [18]:
clusterAssignment = kmeans.predict(df_norm)
clusterAssignment

array([2, 2, 2, ..., 4, 4, 1])

In [17]:
#Print cluster centroids
print(kmeans.cluster_centers_)

[[  5.35098814e-01   1.50166667e-01   0.00000000e+00   2.77777769e-02
    1.66666667e-03   3.02281387e-02   5.42887957e-04   2.67660451e-02
    5.86661900e-04   8.23246433e-01   7.79716377e-01   8.94170356e-01
    7.88760696e-01   2.70665440e-01   6.66372551e-01   2.89386481e-01
    8.94170356e-01   2.11804171e-01   1.25065773e-01]
 [  2.56103232e-01   3.93468137e-01   0.00000000e+00   7.45098018e-02
    1.91176471e-02   7.73428799e-02   4.10042113e-03   6.05736165e-02
    4.96748748e-03   1.48187304e-01   1.38085139e-01   1.85159837e-01
    1.18538808e-01   7.16906282e-01   3.44013845e-01   3.55458216e-01
    1.85413237e-01   4.11986237e-01   2.01889852e-01]
 [  5.13993692e-01   8.08936588e-01   0.00000000e+00   7.74410751e-02
    5.05050505e-03   5.44737633e-02   1.40719343e-03   4.63349822e-02
    1.40097198e-03   1.08789943e-01   9.14029557e-02   9.24140773e-02
    1.42676436e-01   6.79161019e-01   7.90017879e-02   8.21286885e-01
    1.34900800e-01   4.14491323e-01   8.92332630e-01

In [22]:
# Compare your 7 clusters to the 7 pre-assigned classes by computing the Completeness and Homogeneity values of the generated clusters.

#first must convert our labels to numbers
np.unique(labels[0])
t = np.zeros(len(labels),dtype=int)
target = np.array(labels[0])
#print(t)
#print(target)

t[target == 'BRICKFACE'] = 0
t[target == 'CEMENT'] = 1
t[target == 'FOLIAGE'] = 2
t[target == 'GRASS'] = 3
t[target == 'PATH'] = 4
t[target == 'SKY'] = 5
t[target == 'WINDOW'] = 6


In [25]:
print(completeness_score(t,clusterAssignment))

0.612634628644


In [26]:
print(homogeneity_score(t,clusterAssignment))

0.610934710766


###### From the values above, we see there is some disagreement between our assignment and the ones assigned. If  all the data points that are members of a given class are elements of the same cluster, the completeness score would be one. If all the clusters contained  data points that are member of a single class, the homogeneity would be one. 

#### C) Perform PCA on the normalized image data matrix.  Analyze the principal components to determine the number, r, of PCs needed to capture at least 95% of variance in the data. Then use these r components as features to transform the data into a reduced dimension space.

In [33]:
from sklearn import decomposition

pca = decomposition.PCA(n_components=6)
#transform the data
imageTrans = pca.fit(df_norm).transform(df_norm)
np.set_printoptions(precision=2,suppress=True)
print(imageTrans)

[[-0.69  0.53  0.25 -0.2  -0.08  0.05]
 [-0.67  0.51  0.34 -0.17 -0.04  0.06]
 [-0.71  0.77 -0.16 -0.01 -0.17  0.04]
 ..., 
 [-0.51 -0.13 -0.08  0.1  -0.03 -0.03]
 [-0.48 -0.09 -0.16  0.11  0.   -0.  ]
 [-0.44 -0.11 -0.05  0.15  0.02 -0.21]]


In [34]:
print(pca.explained_variance_ratio_)

[ 0.61  0.13  0.1   0.05  0.04  0.02]


In [36]:
var= 0.61+0.13+0.1+0.05+0.04+0.02
print(var)

0.9500000000000001


##### Looking at the above, it can be obsereved that the first 6 components capture about 95% of the variance in the data.

#### D) Perform Kmeans again, but this time on the lower dimensional transformed data. Then, compute the Completeness and Homogeneity values of the new clusters.

In [38]:
kmeans = KMeans(n_clusters=7, max_iter=500, verbose=1)
kmeans.fit(imageTrans)

Initialization complete
start iteration
done sorting
end inner loop
Iteration 0, inertia 303.727821328
start iteration
done sorting
end inner loop
Iteration 1, inertia 284.078165918
start iteration
done sorting
end inner loop
Iteration 2, inertia 280.347368811
start iteration
done sorting
end inner loop
Iteration 3, inertia 279.528779093
start iteration
done sorting
end inner loop
Iteration 4, inertia 278.964617052
start iteration
done sorting
end inner loop
Iteration 5, inertia 278.240773749
start iteration
done sorting
end inner loop
Iteration 6, inertia 277.642412214
start iteration
done sorting
end inner loop
Iteration 7, inertia 277.346011952
start iteration
done sorting
end inner loop
Iteration 8, inertia 277.123780389
start iteration
done sorting
end inner loop
Iteration 9, inertia 277.061573624
start iteration
done sorting
end inner loop
Iteration 10, inertia 277.015585223
start iteration
done sorting
end inner loop
Iteration 11, inertia 276.989244674
start iteration
done sorti

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=500,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=1)

In [40]:
#Compute the completeness and homogeneity values of the new clusters
clusterAssignment2 = kmeans.predict(imageTrans)
print(completeness_score(t,clusterAssignment2))
print(homogeneity_score(t,clusterAssignment2))


0.609967906186
0.608329957268


#### E) Discuss your observations based on the comparison of the two clustering results.
##### After running the PCA, our homogeniety and completeness got closer to zero. Our results are better.¶

##  



### Question 2: Association Rule Discovery with playlists dataset


#### A) Load the playlist data into a Python nested list, and the song_names data into an appropriate data structure.


In [2]:
cd C:\Users\scummings\Desktop\MyFiles\school\csc478_4

C:\Users\scummings\Desktop\MyFiles\school\csc478_4


In [131]:
import apriori_new
import apriori_new as ap


#import apriori4
#import apriori4 as ap



In [117]:
playlist = pd.read_table('playlists/playlists.txt',header=None)
playlist.head()


0
0  0 1 2 3 4 5 6 7 8 
1            9 10 11 
2        12 13 14 15 
3           16 17 18 
4                 19

In [118]:
#data = []
#for line in open('playlists/playlists.txt'):
#    x = [int(i) for i in line.split()]
#    data.append(x)

In [119]:
type(data)

list

In [120]:
songs = np.genfromtxt('playlists/song_names.txt',delimiter='\t',usecols=(1),dtype=(str))
songs.shape

(3168,)

In [121]:
item_meaning = dict((i, songs[i]) for i in range(len(songs)))
playlists = [line.strip().split() for line in open('playlists/playlists.txt').readlines()]
data = []
for s in playlists:
    t = [int(u) for u in s]
    data.append(t)

In [122]:
type(data)
len(data)

41480

#### B) Run Apriori on the playlist data using a min-support value of 0.002.

In [132]:
Lift, Support = ap.apriori(data,0.002)

In [135]:
Lift

[[frozenset({3154}),
  frozenset({2990}),
  frozenset({3055}),
  frozenset({3037}),
  frozenset({2966}),
  frozenset({3110}),
  frozenset({3106}),
  frozenset({2846}),
  frozenset({3112}),
  frozenset({2989}),
  frozenset({2879}),
  frozenset({2871}),
  frozenset({2940}),
  frozenset({3098}),
  frozenset({3094}),
  frozenset({3093}),
  frozenset({2832}),
  frozenset({3086}),
  frozenset({3061}),
  frozenset({3052}),
  frozenset({3059}),
  frozenset({3056}),
  frozenset({3054}),
  frozenset({3006}),
  frozenset({3007}),
  frozenset({2998}),
  frozenset({3004}),
  frozenset({3003}),
  frozenset({2999}),
  frozenset({2997}),
  frozenset({2994}),
  frozenset({2924}),
  frozenset({3051}),
  frozenset({3046}),
  frozenset({2423}),
  frozenset({3031}),
  frozenset({3023}),
  frozenset({3020}),
  frozenset({3019}),
  frozenset({3018}),
  frozenset({3017}),
  frozenset({3016}),
  frozenset({2981}),
  frozenset({2883}),
  frozenset({2872}),
  frozenset({2885}),
  frozenset({2762}),
  frozenset({

#### C) Generate rules from the frequent itemsets discovered in the previous step (you can try different metrics ('lift' or 'confidence' to see which gives you more useful and interesting results). At minimum, you should generate rules with a minimum lift value of 20.0. If you use confidence, you may want to set the min-confidence threshold to about 0.5.

In [136]:
rules = ap.generateRules(Lift, Support, metric='confidence', minMetric=0.5)

frozenset({2883}) --> frozenset({2878}) conf: 0.5281385281385281  lift: 49.90247413937619
frozenset({2832}) --> frozenset({5}) conf: 0.6046511627906976  lift: 36.93804157961434
frozenset({2832}) --> frozenset({2839}) conf: 0.622093023255814  lift: 35.445629951443905
frozenset({2871}) --> frozenset({2839}) conf: 0.5058823529411764  lift: 28.824175824175825
frozenset({2826}) --> frozenset({5}) conf: 0.5852534562211981  lift: 35.75303882776921
frozenset({2871}) --> frozenset({5}) conf: 0.5352941176470587  lift: 32.70103092783504
frozenset({3018}) --> frozenset({3016}) conf: 0.6935483870967741  lift: 243.79989065062873
frozenset({3016}) --> frozenset({3018}) conf: 0.7288135593220338  lift: 243.79989065062873
frozenset({2883}) --> frozenset({5}) conf: 0.5108225108225108  lift: 31.206064431395802
frozenset({2774}) --> frozenset({2018}) conf: 0.5149253731343284  lift: 34.843563585011324
frozenset({2878}) --> frozenset({2839}) conf: 0.5079726651480638  lift: 28.943277679040783
frozenset({2878}

In [126]:
rules

[]

In [137]:
ap.pntRules(rules, songs)

Did-It-On'-Em::Nicki-Minaj
           -------->
Look-At-Me-Now::Chris-Brown
[confidence: 0.528139, lift: 49.902474]

I-Need-A-Doctor::Dr.-Dre
           -------->
Down-On-Me::Jeremih
[confidence: 0.604651, lift: 36.938042]

I-Need-A-Doctor::Dr.-Dre
           -------->
Moment-4-Life::Nicki-Minaj
[confidence: 0.622093, lift: 35.445630]

Written-In-The-Stars::Tinie-Tempah
           -------->
Moment-4-Life::Nicki-Minaj
[confidence: 0.505882, lift: 28.824176]

Back-Seat::New-Boyz
           -------->
Down-On-Me::Jeremih
[confidence: 0.585253, lift: 35.753039]

Written-In-The-Stars::Tinie-Tempah
           -------->
Down-On-Me::Jeremih
[confidence: 0.535294, lift: 32.701031]

Feels-Like::Katchafire
           -------->
Every-Little-Thing::J-Boog
[confidence: 0.693548, lift: 243.799891]

Every-Little-Thing::J-Boog
           -------->
Feels-Like::Katchafire
[confidence: 0.728814, lift: 243.799891]

Did-It-On'-Em::Nicki-Minaj
           -------->
Down-On-Me::Jeremih
[confidence: 0.510823, li

In [138]:
rules2 = ap.generateRules(Lift, Support, metric='lift', minMetric=20.0)

frozenset({2838}) --> frozenset({189}) conf: 0.3082191780821918  lift: 53.04950832717559
frozenset({189}) --> frozenset({2838}) conf: 0.37344398340248963  lift: 53.04950832717558
frozenset({3055}) --> frozenset({2838}) conf: 0.3933649289099526  lift: 55.879374147893266
frozenset({2838}) --> frozenset({3055}) conf: 0.2842465753424657  lift: 55.87937414789326
frozenset({2883}) --> frozenset({3056}) conf: 0.39393939393939387  lift: 57.537345283824145
frozenset({3056}) --> frozenset({2883}) conf: 0.32042253521126757  lift: 57.537345283824145
frozenset({2839}) --> frozenset({2883}) conf: 0.1208791208791209  lift: 21.705913134484565
frozenset({2883}) --> frozenset({2839}) conf: 0.380952380952381  lift: 21.705913134484568
frozenset({2878}) --> frozenset({2883}) conf: 0.27790432801822323  lift: 49.90247413937619
frozenset({2883}) --> frozenset({2878}) conf: 0.5281385281385281  lift: 49.90247413937619
frozenset({635}) --> frozenset({1891}) conf: 0.2514124293785311  lift: 45.34168508965856
froze

In [139]:
ap.pntRules(rules2, songs)

S&M::Rihanna
           -------->
F**k-You::Cee-Lo-Green
[confidence: 0.308219, lift: 53.049508]

F**k-You::Cee-Lo-Green
           -------->
S&M::Rihanna
[confidence: 0.373444, lift: 53.049508]

E.T.-(Futuristic-Lover)::Katy-Perry
           -------->
S&M::Rihanna
[confidence: 0.393365, lift: 55.879374]

S&M::Rihanna
           -------->
E.T.-(Futuristic-Lover)::Katy-Perry
[confidence: 0.284247, lift: 55.879374]

Did-It-On'-Em::Nicki-Minaj
           -------->
Roll-Up::Wiz-Khalifa
[confidence: 0.393939, lift: 57.537345]

Roll-Up::Wiz-Khalifa
           -------->
Did-It-On'-Em::Nicki-Minaj
[confidence: 0.320423, lift: 57.537345]

Moment-4-Life::Nicki-Minaj
           -------->
Did-It-On'-Em::Nicki-Minaj
[confidence: 0.120879, lift: 21.705913]

Did-It-On'-Em::Nicki-Minaj
           -------->
Moment-4-Life::Nicki-Minaj
[confidence: 0.380952, lift: 21.705913]

Look-At-Me-Now::Chris-Brown
           -------->
Did-It-On'-Em::Nicki-Minaj
[confidence: 0.277904, lift: 49.902474]

Did-It-On'-Em

#### D) Identify 3-4 rules and explain why you think they are interesting.

##### Rule 1: F**k-You::Cee-Lo-Green -> S&M::Rihanna

##### Rule 2: Did-It-On'-Em::Nicki-Minaj -> Roll-Up::Wiz-Khalifa

##### Rule 4: Live-A-Little::Kenny-Chesney -> Heart-Like-Mine::Miranda-Lambert

##### From these rules, we find that the recommender system generally picks  songs that are in the same genre to be listened too together. Songs also often have similar themes and tempos. 




##  

### Question 3:Item-Based Joke Recommendation  with Jokes data


#### A) Load in the joke ratings data and the joke text data into appropriate data structures.

In [76]:
import numpy as np
import itemBasedRec4 as itemBasedRec
from numpy import array

import pylab as pl
import pandas as pd
from sklearn.cluster import KMeans 
from sklearn.cross_validation import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import scale

In [77]:
ratings = np.genfromtxt('jokes/modified_jester_data.csv',delimiter=',')
ratings.shape

(1000, 100)

In [78]:
jokes = np.genfromtxt('jokes/jokes.csv',delimiter=',',dtype=str)
jokes = np.array(jokes[:,1])


#### B) Complete the definition for the function "test". This function iterates over all users and for each performs cross-validation on items (by calling the provided "cross_validate_user" function), and returns the error information necessary to compute Mean Absolute Error (MAE). Use this function to perform 5-fold cross-validation (i.e., 20% test-ratio) comparing MAE results using standard item-based collaborative filtering (based on the rating prediction function "standEst") with results using the SVD-based version of the rating item-based CF

In [65]:
def test(dataMat, test_ratio, estMethod):
    total_error=0.0
    total_count=0
    for user in range(dataMat.shape[0]):
        error, count = cross_validate_user(dataMat, user, .2, standEst)
        total_error = total_error + error
        total_count = total_count + count
    MAE = total_error/total_count
    print ('Mean Absoloute Error for ',estMethod,' : ', MAE)
    return MAE
  

In [79]:
itemBasedRec.test(ratings,.2, itemBasedRec.svdEst)

C:\Users\scummings\Desktop\MyFiles\school\csc478_4\itemBasedRec4.py:70: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  test_indices = np.random.randint(0, len(rated_items_by_user), test_size)


Mean Absoloute Error for  <function svdEst at 0x000000000EC21D90>  :  3.69445323243


3.6944532324294133

In [80]:
itemBasedRec.test(ratings, .2, itemBasedRec.standEst)

C:\Users\scummings\Desktop\MyFiles\school\csc478_4\itemBasedRec4.py:70: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  test_indices = np.random.randint(0, len(rated_items_by_user), test_size)


Mean Absoloute Error for  <function standEst at 0x000000000EC21D08>  :  3.69964260521


3.6996426052097671

#### C) Write a new function "print_most_similar_jokes" which takes the joke ratings data, a query joke id, a parameter k for the number of nearest neighbors, and a similarity metric function, and prints the text of the query joke as well as the texts of the top k most similar jokes based on user ratings. 

In [67]:
def pearsSim(inA,inB):
    if len(inA) < 3 : return 1.0
    return 0.5 + 0.5 * corrcoef(inA, inB, rowvar = 0)[0][1]

In [68]:
def print_most_similar_jokes(dataMat, jokes, queryJoke, k, metric=pearsSim):
    print("Selcted joke: ")
    print()
    print(jokes[queryJoke])
    print()
    dataMatArray = np.array(dataMat)
    knn, indicies = kNearestNeighbors(queryJokeVector, dataMat, k, metric)	
    print ("The top %d recommended jokes are: "%(k))
    for ind in indicies:
        jok = jokes[ind]
        print()
        print (jok)

In [81]:
itemBasedRec.print_most_similar_jokes(ratings, jokes, 3, 5, itemBasedRec.pearsSim)

Selcted joke: 

Q. What's the difference between a man and a toilet? A. A toilet doesn't follow you around after you use it.

The top 5 recommended jokes are: 

A dog walks into Western Union and asks the clerk to send a telegram. He fills out a form on which he writes down the telegram he wishes to send: "Bow wow wow Bow wow wow."The clerk says "You can add another 'Bow wow' for the same price."The dog responded "Now wouldn't that sound a little silly?"

Q:  What did the blind person say when given some matzah?A:  Who the hell wrote this?

Q. Did you hear about the dyslexic devil worshipper? A. He sold his soul to Santa.

Q. What is orange and sounds like a parrot?  A. A carrot.

A guy goes into confession and says to the priest "Father I'm 80 years old widower with 11 grandchildren. Last night I met two beautiful flight attendants. They took me home and I made love to both of them. Twice."The priest said: "Well my son when was the last time you were in confession?" "Never Father I'm 